# Generated by Django 2.0.6 on 2018-09-27 01:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date(2018, 9, 27), verbose_name="date d'émission")),
                ('end', models.DateField(default=datetime.date(2019, 9, 27), verbose_name='Fin')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Adhérent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(default='admin', max_length=50)),
                ('contenu', models.TextField(null=True)),
                ('lien', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='photos/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('nb_cours', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('created', models.DateField(default=datetime.date(2018, 9, 27), verbose_name="date d'émission")),
                ('last', models.DateField(default=datetime.date(2019, 9, 27), verbose_name="date d'échéance")),
                ('to_user_firstname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_lastname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_address', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_city', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_zipcode', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_siret', models.CharField(blank=True, default='SIRET', max_length=21, null=True)),
                ('to_user_sap', models.CharField(blank=True, default='SAP', max_length=11, null=True)),
                ('from_user_firstname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_lastname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_address', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_city', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_zipcode', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_siret', models.CharField(blank=True, default='SIRET', max_length=21, null=True)),
                ('from_user_sap', models.CharField(blank=True, default='SAP', max_length=11, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_professor', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date(2018, 9, 28), verbose_name='Début')),
                ('end', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_cours', models.SmallIntegerField(default=0, verbose_name='Durée des cours')),
                ('mois', models.CharField(max_length=7)),
                ('is_valid_t', models.BooleanField(default=False)),
                ('is_valid_s', models.BooleanField(default=False)),
                ('is_unvalid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(default=None, max_length=100)),
                ('referent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=340)),
                ('last', models.DateField(default=datetime.date(2018, 10, 27), verbose_name='Clôture des inscriptions')),
                ('price', models.FloatField(default=40.0, max_length=5, verbose_name="Prix de l'examen par élèves")),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=None)),
                ('price_ht', models.FloatField(default=None)),
                ('price_ttc', models.FloatField(default=None)),
                ('object', models.CharField(default=None, max_length=60)),
                ('object_qt', models.FloatField(default=None)),
                ('h_qt', models.FloatField(blank=True, default=None, null=True)),
                ('type', models.CharField(default=None, max_length=60)),
                ('created', models.DateField(default=datetime.date(2018, 9, 27), verbose_name="date d'émission")),
                ('last', models.DateField(default=datetime.date(2018, 10, 4), verbose_name="date d'échéance")),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('facture_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('nb_facture', models.IntegerField(default=1)),
                ('to_user_firstname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_lastname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_address', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_city', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_zipcode', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('to_user_siret', models.CharField(blank=True, default='SIRET', max_length=21, null=True)),
                ('to_user_sap', models.CharField(blank=True, default='SAP', max_length=11, null=True)),
                ('from_user_firstname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_lastname', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_address', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_city', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_zipcode', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('from_user_siret', models.CharField(blank=True, default='SIRET', max_length=21, null=True)),
                ('from_user_sap', models.CharField(blank=True, default='SAP', max_length=11, null=True)),
                ('from_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_who_send_the_bill', to=settings.AUTH_USER_MODEL, verbose_name='Emetteur')),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_who_received_the_bill', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Eleve', to='intranet.Eleve')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examen', to='intranet.Examen')),
            ],
            options={
                'verbose_name_plural': 'Inscriptions Examens',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(validators=[django.core.validators.RegexValidator(regex='^[0-9a-f-]+$')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_h', models.SmallIntegerField(default=0, verbose_name='Heures')),
                ('nb_m', models.SmallIntegerField(default=0, verbose_name='Minutes')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mois', models.CharField(max_length=7)),
                ('is_valid_t', models.BooleanField(default=False)),
                ('is_valid_s', models.BooleanField(default=False)),
                ('is_unvalid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Leçons',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('object', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=340)),
                ('from_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_who_send_the_notification', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_who_received_the_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date(2018, 9, 28), verbose_name='Début')),
                ('end', models.DateField(blank=True, default=None, null=True, verbose_name='Fin')),
                ('tva', models.FloatField(default=20.0, max_length=5)),
                ('adhesion', models.FloatField(default=66.67, max_length=5)),
                ('adhesion_reduc', models.FloatField(default=60, max_length=5)),
                ('adhesion_prof', models.FloatField(blank=True, default=15.83, max_length=5)),
                ('cours', models.FloatField(default=41.0, max_length=5)),
                ('cours_premium', models.FloatField(blank=True, default=51.0, max_length=5)),
                ('cours_ecole', models.FloatField(blank=True, default=40.0, max_length=5)),
                ('commission', models.FloatField(default=0.83, max_length=5)),
                ('frais_gestion', models.FloatField(default=7.5, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Prix',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_in_relation_model', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_in_relation_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2018, 9, 27))),
                ('nb_prof', models.IntegerField(blank=True, default=0, null=True)),
                ('nb_user', models.IntegerField(blank=True, default=0, null=True)),
                ('nb_eleve', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statistiques',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit suivre le format XX.XX.XX.XX.XX', regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')])),
                ('address', models.CharField(default='', max_length=60)),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='France', max_length=50)),
                ('lat', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('lgn', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Le Code Postal doit suivre le format DDDDD', regex='^(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}$')])),
                ('is_adherent', models.BooleanField(default=False)),
                ('siret', models.CharField(blank=True, default='SIRET', max_length=21)),
                ('sap', models.CharField(blank=True, default='SAP', max_length=11)),
                ('nb_facture', models.IntegerField(default=1)),
                ('stats', models.CharField(blank=True, choices=[('A', 'Moteur de recherche Google'), ('B', 'Facebook'), ('C', 'Autre source internet'), ('D', 'Annuaire(pages jaunes...)'), ('E', 'Nebout & Hamm'), ('F', 'Falado'), ('G', 'Connaissance(famille, amis...)')], max_length=1, null=True)),
                ('is_premium', models.BooleanField(default=False, help_text="Permet d'annuler un cours à la dernière minute, les cours sont majorés de 10€.")),
                ('stripe_account_id', models.CharField(blank=True, default='StripeAccId', help_text='ex: acct_1D5xIp...', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Relation'),
        ),
        migrations.AddField(
            model_name='cour',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Relation'),
        ),
    ]
