# Generated by Django 2.0.6 on 2018-09-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='h_qt',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
