# Generated by Django 2.0.6 on 2018-09-03 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 17, 15, 43, 1845)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sap',
            field=models.CharField(blank=True, default='SAP', max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='siret',
            field=models.CharField(blank=True, default='SIRET', max_length=21),
        ),
    ]
