# Generated by Django 2.0.6 on 2018-09-04 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20180903_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 4), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 9, 4), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 4), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 9, 11), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 10, 2, 59, 800268)),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 9, 5), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lat',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lgn',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
