# Generated by Django 2.0.6 on 2018-09-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_attestation_h_qt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nb_adh',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
