# Generated by Django 2.0.6 on 2018-10-03 08:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_attestation_nb_adh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhesion',
            options={'verbose_name': 'adhésion', 'verbose_name_plural': 'adhésions'},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'élève', 'verbose_name_plural': 'élèves'},
        ),
        migrations.AddField(
            model_name='attestation',
            name='admin_address',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='admin_city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='admin_zipcode',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='admin_address',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='admin_city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='admin_zipcode',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 3), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='end',
            field=models.DateField(default=datetime.date(2019, 10, 3), verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Adhérent', to=settings.AUTH_USER_MODEL, verbose_name='Adhérent'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 3), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_professor', to=settings.AUTH_USER_MODEL, verbose_name='Emetteur'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 10, 3), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='nb_cours',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Nombre de cours'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='price',
            field=models.SmallIntegerField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_student', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='end',
            field=models.BooleanField(default=False, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 4), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='cour',
            name='is_unvalid',
            field=models.BooleanField(default=False, verbose_name='Désaccord'),
        ),
        migrations.AlterField(
            model_name='cour',
            name='is_valid_s',
            field=models.BooleanField(default=False, verbose_name="Validé par l'élève"),
        ),
        migrations.AlterField(
            model_name='cour',
            name='is_valid_t',
            field=models.BooleanField(default=False, verbose_name="Validé par l'enseignant"),
        ),
        migrations.AlterField(
            model_name='examen',
            name='description',
            field=models.CharField(max_length=340, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='last',
            field=models.DateField(default=datetime.date(2018, 11, 2), verbose_name='Clôture des inscriptions'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 3), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='h_qt',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 10, 10), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='inscriptionexamen',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Eleve', to='intranet.Eleve', verbose_name='Élève'),
        ),
        migrations.AlterField(
            model_name='inscriptionexamen',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examen', to='intranet.Examen', verbose_name='Examen'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Adh. Gratuit'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Professeur'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_unvalid',
            field=models.BooleanField(default=False, verbose_name='Désaccord'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_valid_s',
            field=models.BooleanField(default=False, verbose_name="Validé par l'élève"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_valid_t',
            field=models.BooleanField(default=False, verbose_name="Validé par l'enseignant"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_who_send_the_notification', to=settings.AUTH_USER_MODEL, verbose_name='Emetteur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_who_received_the_notification', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 4), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='prix',
            name='tva',
            field=models.FloatField(default=20.0, max_length=5, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_in_relation_model', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_in_relation_model', to=settings.AUTH_USER_MODEL, verbose_name='Professeur'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 3)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=60, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='France', max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit suivre le format XX.XX.XX.XX.XX', regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sap',
            field=models.CharField(default='SAP', max_length=11, verbose_name='SAP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='siret',
            field=models.CharField(default='SIRET', max_length=21, verbose_name='SIRET'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stats',
            field=models.CharField(choices=[('A', 'Moteur de recherche Google'), ('B', 'Facebook'), ('C', 'Autre source internet'), ('D', 'Annuaire(pages jaunes...)'), ('E', 'Nebout & Hamm'), ('F', 'Falado'), ('G', 'Connaissance(famille, amis...)')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Le code postal doit suivre le format DDDDD', regex='^(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}$')], verbose_name='Code Postal'),
        ),
    ]
