# Generated by Django 2.0.6 on 2018-10-04 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20181004_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nots_view',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date des dernières modifications'),
        ),
    ]
