# Generated by Django 2.0.6 on 2018-09-13 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20180911_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='prenom',
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_prenom',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_address',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_firstname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_lastname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_sap',
            field=models.CharField(blank=True, default='SAP', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_siret',
            field=models.CharField(blank=True, default='SIRET', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='from_user_zipcode',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='nb_facture',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_address',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_firstname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_lastname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_sap',
            field=models.CharField(blank=True, default='SAP', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_siret',
            field=models.CharField(blank=True, default='SIRET', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='to_user_zipcode',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 13), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 9, 13), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 13), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 9, 20), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 9, 14), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 13)),
        ),
    ]
