# Generated by Django 2.0.6 on 2018-10-06 17:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_auto_20181004_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 6), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='end',
            field=models.DateField(default=datetime.date(2019, 10, 6), verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 6), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 10, 6), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='condition',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 7), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='referent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examen',
            name='last',
            field=models.DateField(default=datetime.date(2018, 11, 5), verbose_name='Clôture des inscriptions'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 6), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 10, 13), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 7), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 6)),
        ),
    ]
