# Generated by Django 2.0.6 on 2018-10-06 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_auto_20181006_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='referent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
