# Generated by Django 2.0.6 on 2018-10-10 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_auto_20181006_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 10), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='end',
            field=models.DateField(default=datetime.date(2019, 10, 10), verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 10), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 10, 10), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='condition',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 11), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='last',
            field=models.DateField(default=datetime.date(2018, 11, 9), verbose_name='Clôture des inscriptions'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 10, 10), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 10, 17), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 11), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 10)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stats',
            field=models.CharField(choices=[('A', 'Moteur de recherche (Google, Yahoo...)'), ('B', 'Réseau social (Facebook, Twitter...)'), ('C', 'Connaissance (famille, amis...)'), ('D', 'Librairie musicale Falado'), ('E', 'Nebout & Hamm'), ('F', 'Annuaire en ligne (Pages jaunes, Yelp...)'), ('G', 'Prospectus, flyers'), ('H', 'Autre')], max_length=1, null=True),
        ),
    ]
