# Generated by Django 2.0.6 on 2018-09-15 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_auto_20180915_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_h', models.SmallIntegerField(default=0, verbose_name='Heures')),
                ('nb_m', models.SmallIntegerField(default=0, verbose_name='Minutes')),
                ('date', models.DateField(default=datetime.datetime(2018, 9, 15, 15, 3, 54, 276989, tzinfo=utc))),
                ('mois', models.CharField(max_length=7)),
                ('is_valid_t', models.BooleanField(default=False)),
                ('is_valid_s', models.BooleanField(default=False)),
                ('is_unvalid', models.BooleanField(default=False)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.Relation')),
            ],
        ),
    ]
