# Generated by Django 2.0.6 on 2018-09-16 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prix',
            options={'verbose_name_plural': 'Prix'},
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 16), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 9, 16), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 16), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 9, 23), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 16, 17, 13, 28, 425880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prix',
            name='cours_ecole',
            field=models.FloatField(blank=True, default=40.0, max_length=5),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 9, 17), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 16)),
        ),
    ]
