# Generated by Django 2.0.6 on 2018-09-16 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_auto_20180916_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='from_user_address',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='from_user_city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='from_user_firstname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='from_user_lastname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='from_user_sap',
            field=models.CharField(blank=True, default='SAP', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='from_user_siret',
            field=models.CharField(blank=True, default='SIRET', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='from_user_zipcode',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_address',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_city',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_firstname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_lastname',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_sap',
            field=models.CharField(blank=True, default='SAP', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_siret',
            field=models.CharField(blank=True, default='SIRET', max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='attestation',
            name='to_user_zipcode',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 16, 20, 8, 58, 391466, tzinfo=utc)),
        ),
    ]
