# Generated by Django 2.0.6 on 2018-09-16 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_auto_20180916_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='nb_cours',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 16, 20, 33, 44, 739448, tzinfo=utc)),
        ),
    ]
