# Generated by Django 2.0.6 on 2018-09-17 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_auto_20180917_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='condi',
        ),
        migrations.AddField(
            model_name='condition',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 21, 20, 16, 874108, tzinfo=utc)),
        ),
    ]
