# Generated by Django 2.0.6 on 2018-09-17 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_auto_20180917_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 21, 29, 10, 801721, tzinfo=utc)),
        ),
    ]
