# Generated by Django 2.0.6 on 2018-09-19 19:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_auto_20180918_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='StripeId', max_length=40),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 19), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='end',
            field=models.DateField(default=datetime.date(2019, 9, 19), verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 19), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='last',
            field=models.DateField(default=datetime.date(2019, 9, 19), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='condition',
            name='start',
            field=models.DateField(default=datetime.date(2018, 9, 20), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='created',
            field=models.DateField(default=datetime.date(2018, 9, 19), verbose_name="date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='from_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_who_send_the_bill', to=settings.AUTH_USER_MODEL, verbose_name='Emetteur'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='last',
            field=models.DateField(default=datetime.date(2018, 9, 26), verbose_name="date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_who_received_the_bill', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 19, 19, 49, 45, 239646, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prix',
            name='start',
            field=models.DateField(default=datetime.date(2018, 9, 20), verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 19)),
        ),
    ]
