# Generated by Django 2.0.6 on 2018-09-20 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_auto_20180920_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 20, 13, 18, 6, 98921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='StripeAccId', help_text='ex: acct_1D5xIp...', max_length=40),
        ),
    ]
