# Generated by Django 2.0.6 on 2018-09-20 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_auto_20180920_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 20, 14, 25, 2, 492115, tzinfo=utc)),
        ),
    ]
