# Generated by Django 2.0.6 on 2018-09-20 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0021_auto_20180920_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
